### ISSUE TITLE
can't hide loading alert

### ISSUE THREAD

**Issue by albae69** [aldyrifaldi/Alternative-Alert#4]
when i viewing your alternative alert, i think u forget to give some close button at loading alert pre-view.

**Comment by aldyrifaldi** [comment]
thanks for your advice, alternative alert under develop right now. i hope
you can join to.


Pada tanggal Sel, 24 Nov 2020 pukul 18.14 bae <notifications@github.com>
menulis:

**Comment by aldyrifaldi** [comment]
Check it out

> when i viewing your alternative alert, i think u forget to give some close button at loading alert pre-view.
You can check it right now
